# -*- coding: utf-8 -*-
"""Exercise 3.4 Understanding your classification data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnsqY5ZVt5zdWwGLKrfER_2fLganisIt

## Exercise 3.4 Understanding your classification data
Now you will start modeling with a new dataset for a classification problem. This data includes information about passengers on the Titanic. You will use predictors such as `age`, `fare` and where each passenger `embarked` from to predict who will survive.

You can download the .csv file from the following link:

[titanic_all_numeric.csv](https://drive.google.com/file/d/11nuYS-l3EXCsGJt81y4YTt3oTnFGaB68/view?usp=drive_link)

The data is pre-loaded into a pandas DataFrame called `df`. You can Use the `head()` and `describe()` methods for a quick overview of the DataFrame.

In this exercise, you will practice performing some exploratory analysis on your data to figure out: What was the maximum age of passengers on the Titanic?

## Instructions

* The min and max values as shown by `describe()` will be informative here.
What was the maximum age of passengers on the Titanic?
  * 29.699
  * 80
  * 891
  * It is not listed

## Code
"""

import pandas as pd
# Load csv file into the dataframe: df
df = pd.read_csv("titanic_all_numeric.csv")

"""Perfome exploratory analysis using `head()` and `describe()` methods"""

print(df.head())
print(df.describe())