# -*- coding: utf-8 -*-
"""Exercise 3.1 Understanding your data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PBBzb3cxx3xJkqbgkY73aIWvHrLTWWPg

## Exercise 3.1 Understanding your data
You will soon start building models in Keras to predict wages based on various professional and demographic factors.

Before you start building a model, it's good to understand your data by performing some exploratory analysis.

In this exercise, you will work with a .csv file that contains some data about workers in a company. You can download this file from the following link:

[hourly_wages.csv](https://drive.google.com/file/d/1elGBb48CX728knwJzU3ImHNvtuRoG7vu/view?usp=drive_link)

The data is pre-loaded into a pandas DataFrame called `df`. You can Use the `head()` and `describe()` methods for a quick overview of the DataFrame.

The target variable you'll be predicting is wage_per_hour. Some of the predictor variables are binary indicators, where a value of 1 represents True, and 0 represents False.

In this exercise, you will practice performing some exploratory analysis on your data to figure out: Of the 9 predictor variables in the DataFrame, how many are binary indicators?

## Instructions

* The min and max values as shown by `describe()` will be informative here.
How many binary indicator predictors are there?
  * 0
  * 5
  * 6

RESULT

Number of binary predictors: 6

## Code
"""

import pandas as pd
# Load csv file into the dataframe: df
df = pd.read_csv("hourly_wages.csv")

"""Perfome exploratory analysis using `head()` and `describe()` methods"""

df.head()

df.describe()